-- MySQL Script generated by MySQL Workbench
-- 11/10/24 22:12:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Conecta2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Conecta2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Conecta2` DEFAULT CHARACTER SET utf8 ;
USE `Conecta2` ;

-- -----------------------------------------------------
-- Table `Conecta2`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Conecta2`.`Usuario` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `Género` ENUM('M', 'F') NULL,
  `email` VARCHAR(100) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `pregunta_de_seguridad` VARCHAR(100) NOT NULL,
  `respuesta_de_seguridad` VARCHAR(100) NOT NULL,
  `fecha_de_nacimiento` DATE NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Conecta2`.`Publicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Conecta2`.`Publicacion` (
  `pub_id` INT NOT NULL AUTO_INCREMENT,
  `contenido` VARCHAR(500) NULL,
  `imagen` VARCHAR(100) NULL,
  `fecha_y_hora` TIMESTAMP NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`pub_id`, `user_id`),
  INDEX `fk_Publicacion_Usuario_idx` (`user_id` ASC),
  CONSTRAINT `fk_Publicacion_Usuario`
    FOREIGN KEY (`user_id`)
    REFERENCES `Conecta2`.`Usuario` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Conecta2`.`Comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Conecta2`.`Comentario` (
  `com_id` INT NOT NULL AUTO_INCREMENT,
  `contenido` VARCHAR(300) NOT NULL,
  `fecha_y_hora` TIMESTAMP NOT NULL,
  `pub_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`com_id`, `pub_id`, `user_id`),
  INDEX `fk_Comentario_Publicacion1_idx` (`pub_id` ASC),
  INDEX `fk_Comentario_Usuario1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Comentario_Publicacion1`
    FOREIGN KEY (`pub_id`)
    REFERENCES `Conecta2`.`Publicacion` (`pub_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentario_Usuario1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Conecta2`.`Usuario` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Conecta2`.`Like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Conecta2`.`Like` (
  `like_id` INT NOT NULL,
  `fecha_y_hora` TIMESTAMP NOT NULL,
  `pub_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`like_id`, `pub_id`, `user_id`),
  INDEX `fk_Like_Publicacion1_idx` (`pub_id` ASC),
  INDEX `fk_Like_Usuario1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Like_Publicacion1`
    FOREIGN KEY (`pub_id`)
    REFERENCES `Conecta2`.`Publicacion` (`pub_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Like_Usuario1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Conecta2`.`Usuario` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Conecta2`.`Seguir`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Conecta2`.`Seguir` (
  `seg_id` INT NOT NULL AUTO_INCREMENT,
  `fecha_y_hora` TIMESTAMP NOT NULL,
  `seguidor_id` INT NOT NULL,
  `siguiendo_id` INT NOT NULL,
  PRIMARY KEY (`seg_id`, `seguidor_id`, `siguiendo_id`),
  INDEX `fk_Seguir_Usuario1_idx` (`seguidor_id` ASC),
  INDEX `fk_Seguir_Usuario2_idx` (`siguiendo_id` ASC),
  CONSTRAINT `fk_Seguir_Usuario1`
    FOREIGN KEY (`seguidor_id`)
    REFERENCES `Conecta2`.`Usuario` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Seguir_Usuario2`
    FOREIGN KEY (`siguiendo_id`)
    REFERENCES `Conecta2`.`Usuario` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Conecta2`.`Notificacion_segui`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Conecta2`.`Notificacion_segui` (
  `notifi_id` INT NOT NULL AUTO_INCREMENT,
  `seg_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`notifi_id`, `seg_id`, `user_id`),
  INDEX `fk_Notificacion_segui_Seguir1_idx` (`seg_id` ASC),
  INDEX `fk_Notificacion_segui_Usuario1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Notificacion_segui_Seguir1`
    FOREIGN KEY (`seg_id`)
    REFERENCES `Conecta2`.`Seguir` (`seg_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notificacion_segui_Usuario1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Conecta2`.`Usuario` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Conecta2`.`Notificacion_like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Conecta2`.`Notificacion_like` (
  `notifi_id` INT NOT NULL AUTO_INCREMENT,
  `like_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`notifi_id`, `like_id`, `user_id`),
  INDEX `fk_Notificacion_like_Like1_idx` (`like_id` ASC),
  INDEX `fk_Notificacion_like_Usuario1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Notificacion_like_Like1`
    FOREIGN KEY (`like_id`)
    REFERENCES `Conecta2`.`Like` (`like_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notificacion_like_Usuario1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Conecta2`.`Usuario` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Conecta2`.`Notificacion_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Conecta2`.`Notificacion_comment` (
  `notifi_id` INT NOT NULL AUTO_INCREMENT,
  `Usuario_user_id` INT NOT NULL,
  `com_id` INT NOT NULL,
  PRIMARY KEY (`notifi_id`, `Usuario_user_id`, `com_id`),
  INDEX `fk_Notificacion_comment_Usuario1_idx` (`Usuario_user_id` ASC),
  INDEX `fk_Notificacion_comment_Comentario1_idx` (`com_id` ASC),
  CONSTRAINT `fk_Notificacion_comment_Usuario1`
    FOREIGN KEY (`Usuario_user_id`)
    REFERENCES `Conecta2`.`Usuario` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notificacion_comment_Comentario1`
    FOREIGN KEY (`com_id`)
    REFERENCES `Conecta2`.`Comentario` (`com_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
